### PR TITLE
Draft:feat: independant appflowy collab websocket server

### PR DESCRIPTION
**Pull request by khorshuheng**
This is the draft PR based on the version 3 design as proposed in https://github.com/AppFlowy-IO/AppFlowy-Cloud/issues/411#issuecomment-2030966504 . CollabStorage implementation is just a placeholder at the moment.

If we allow both the collab service and the api server to manipulate the collab storage directly, then we will need to extract the relevant functionality into a separate crate. Alternatively, we can make the collab storage the sole responsibility of the collab service, then the API server will update the collab storage indirectly via http calls to the collab service.

### CODE REVIEW

**Comment by appflowy** [comment]
Hi @khorshuheng. It seems like you didn't pull the latest main branch code. Because I saw appflowy-collaborate is different from the main branch

**Comment by khorshuheng** [comment]
> Hi @khorshuheng. It seems like you didn't pull the latest main branch code. Because I saw appflowy-collaborate is different from the main branch

Noted, I have probably missed some updates when i go through the past PRs. Apart from storage.rs, which i am still working on, is there any other difference that you have noticed? I will amend it.

**Comment by khorshuheng** [comment]
Current state:
- The ws connection tests passed.
- Unable to pass the collab test at the moment. Currently, the get collab endpoint is served by the Appflowy cloud service as opposed to the independent collab service. This involves retrieving CollabGroup from the in-memory dashmap. For the current test to pass, the get collab endpoint and the collab websocket service has to be served from the same server.

**Comment by khorshuheng** [comment]
Closing this as this is replaced by https://github.com/AppFlowy-IO/AppFlowy-Cloud/pull/640 .

**Pull request closed without merging**
