### PR TITLE
refactor(docker): Update docker to quick start the project

### LINKED ISSUE #10: [Bug] Error on docker compose build
**Describe the bug**
I try to launch the application using the `docker-compose.yml` file with the command line

```bash
docker compose up -d --build && docker compose logs -f
```

**To Reproduce**
1. Checkout the code
2. Launch the command line
```bash
docker compose up -d --build && docker compose logs -f
```
3. Resulting error:
```
57.20 error: package `time-macros v0.2.11` cannot be built because it requires rustc 1.67.0 or newer, while the currently active rustc version is 1.65.0
57.20 Either upgrade to rustc 1.67.0 or newer, or use
57.20 cargo update -p time-macros@0.2.11 --precise ver
57.20 where `ver` is the latest version of `time-macros` supporting rustc 1.65.0
57.20 thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.50/src/recipe.rs:176:27
57.20 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------
failed to solve: process "/bin/sh -c cargo chef cook --release --recipe-path recipe.json" did not complete successfully: exit code: 101
```

**Expected behavior**
The application is built and ran in docker

**Desktop (please complete the following information):**
 - OS: Linux (ubuntu 22.04)
 - Docker 24.0.5
 - Docker compose v2.20.2

**Additional context**
None

### PR DESCRIPTION
**Pull request by vvatelot**
closes #10

### CODE REVIEW

**Comment by vvatelot** [comment]
After doing this, containers starts, but I now trigger an error:

```
appflowy-cloud-appflowy_cloud-1  | thread 'main' panicked at 'Failed to read configuration.: missing field `gotrue`', src/main.rs:14:43
appflowy-cloud-appflowy_cloud-1  | stack backtrace:
appflowy-cloud-appflowy_cloud-1  |    0:     0x559e33ab9041 - std::backtrace_rs::backtrace::libunwind::trace::he648b5c8dd376705
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
appflowy-cloud-appflowy_cloud-1  |    1:     0x559e33ab9041 - std::backtrace_rs::backtrace::trace_unsynchronized::h5da3e203eef39e9f
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
appflowy-cloud-appflowy_cloud-1  |    2:     0x559e33ab9041 - std::sys_common::backtrace::_print_fmt::h8d28d3f20588ae4c
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:65:5
appflowy-cloud-appflowy_cloud-1  |    3:     0x559e33ab9041 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd9a5b0c9c6b058c0
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:44:22
appflowy-cloud-appflowy_cloud-1  |    4:     0x559e33ae66bf - core::fmt::rt::Argument::fmt::h0afc04119f252b53
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/rt.rs:138:9
appflowy-cloud-appflowy_cloud-1  |    5:     0x559e33ae66bf - core::fmt::write::h50b1b3e73851a6fe
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/mod.rs:1094:21
appflowy-cloud-appflowy_cloud-1  |    6:     0x559e33ab55b7 - std::io::Write::write_fmt::h184eaf275e4484f0
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/io/mod.rs:1714:15
appflowy-cloud-appflowy_cloud-1  |    7:     0x559e33ab8e55 - std::sys_common::backtrace::_print::hf58c3a5a25090e71
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:47:5
appflowy-cloud-appflowy_cloud-1  |    8:     0x559e33ab8e55 - std::sys_common::backtrace::print::hb9cf0a7c7f077819
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:34:9
appflowy-cloud-appflowy_cloud-1  |    9:     0x559e33aba5c3 - std::panicking::default_hook::{{closure}}::h066adb2e3f3e2c07
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:269:22
appflowy-cloud-appflowy_cloud-1  |   10:     0x559e33aba354 - std::panicking::default_hook::h277fa2776900ff14
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:288:9
appflowy-cloud-appflowy_cloud-1  |   11:     0x559e33abab49 - std::panicking::rust_panic_with_hook::hceaf38da6d9db792
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:705:13
appflowy-cloud-appflowy_cloud-1  |   12:     0x559e33abaa47 - std::panicking::begin_panic_handler::{{closure}}::h2bce3ed2516af7df
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:597:13
appflowy-cloud-appflowy_cloud-1  |   13:     0x559e33ab94a6 - std::sys_common::backtrace::__rust_end_short_backtrace::h090f3faf8f98a395
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:151:18
appflowy-cloud-appflowy_cloud-1  |   14:     0x559e33aba792 - rust_begin_unwind
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
appflowy-cloud-appflowy_cloud-1  |   15:     0x559e32c36063 - core::panicking::panic_fmt::h4ec8274704d163a3
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
appflowy-cloud-appflowy_cloud-1  |   16:     0x559e32c36503 - core::result::unwrap_failed::h170bc2721a6c6ff2
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
appflowy-cloud-appflowy_cloud-1  |   17:     0x559e32c7ff05 - appflowy_cloud::main::{{closure}}::h5d08a05b217815de
appflowy-cloud-appflowy_cloud-1  |   18:     0x559e32c7eb92 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::hf0e3f75cfa232c78
appflowy-cloud-appflowy_cloud-1  |   19:     0x559e32d52847 - <core::pin::Pin<P> as core::future::future::Future>::poll::h3986a356dc03807f
appflowy-cloud-appflowy_cloud-1  |   20:     0x559e32d6d48a - tokio::runtime::scheduler::current_thread::Context::enter::h595885efec386e4d
appflowy-cloud-appflowy_cloud-1  |   21:     0x559e32c7b8ef - tokio::runtime::context::scoped::Scoped<T>::set::h752a37851ffdc298
appflowy-cloud-appflowy_cloud-1  |   22:     0x559e32cbce00 - tokio::runtime::context::set_scheduler::h0266dd634944a54a
appflowy-cloud-appflowy_cloud-1  |   23:     0x559e32d6d88c - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::h18b8ae32d93cfafb
appflowy-cloud-appflowy_cloud-1  |   24:     0x559e32ca8fcc - tokio::runtime::context::runtime::enter_runtime::hc0748e020bcc976d
appflowy-cloud-appflowy_cloud-1  |   25:     0x559e32d516b0 - tokio::runtime::runtime::Runtime::block_on::h6ecd33bdab2f0eb7
appflowy-cloud-appflowy_cloud-1  |   26:     0x559e32d65433 - appflowy_cloud::main::h576b8397a210569b
appflowy-cloud-appflowy_cloud-1  |   27:     0x559e32d05013 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8eee212e491cb454
appflowy-cloud-appflowy_cloud-1  |   28:     0x559e32d0502d - std::rt::lang_start::{{closure}}::h632ac5dc0e60e8fe
appflowy-cloud-appflowy_cloud-1  |   29:     0x559e33aae9bb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h75ba4244a1c7bb54
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:284:13
appflowy-cloud-appflowy_cloud-1  |   30:     0x559e33aae9bb - std::panicking::try::do_call::h0a2baa36dea975a1
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
appflowy-cloud-appflowy_cloud-1  |   31:     0x559e33aae9bb - std::panicking::try::h0e42aa233d4224d4
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
appflowy-cloud-appflowy_cloud-1  |   32:     0x559e33aae9bb - std::panic::catch_unwind::hefdfd8f482606434
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
appflowy-cloud-appflowy_cloud-1  |   33:     0x559e33aae9bb - std::rt::lang_start_internal::{{closure}}::h457959f0f91da23b
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:48
appflowy-cloud-appflowy_cloud-1  |   34:     0x559e33aae9bb - std::panicking::try::do_call::h112cfd1acb38183b
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
appflowy-cloud-appflowy_cloud-1  |   35:     0x559e33aae9bb - std::panicking::try::ha64f15b20cec18ca
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
appflowy-cloud-appflowy_cloud-1  |   36:     0x559e33aae9bb - std::panic::catch_unwind::hbacc2b68ee2c119e
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
appflowy-cloud-appflowy_cloud-1  |   37:     0x559e33aae9bb - std::rt::lang_start_internal::h5f408694586c2a05
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:20
appflowy-cloud-appflowy_cloud-1  |   38:     0x559e32d65495 - main
appflowy-cloud-appflowy_cloud-1  |   39:     0x7f177bc921ca - <unknown>
appflowy-cloud-appflowy_cloud-1  |   40:     0x7f177bc92285 - __libc_start_main
appflowy-cloud-appflowy_cloud-1  |   41:     0x559e32c64951 - _start
appflowy-cloud-appflowy_cloud-1  |   42:                0x0 - <unknown>
appflowy-cloud-appflowy_cloud-1  | thread 'main' panicked at 'Failed to read configuration.: missing field `gotrue`', src/main.rs:14:43
appflowy-cloud-appflowy_cloud-1  | stack backtrace:
appflowy-cloud-appflowy_cloud-1  |    0:     0x55fe72414041 - std::backtrace_rs::backtrace::libunwind::trace::he648b5c8dd376705
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
appflowy-cloud-appflowy_cloud-1  |    1:     0x55fe72414041 - std::backtrace_rs::backtrace::trace_unsynchronized::h5da3e203eef39e9f
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
appflowy-cloud-appflowy_cloud-1  |    2:     0x55fe72414041 - std::sys_common::backtrace::_print_fmt::h8d28d3f20588ae4c
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:65:5
appflowy-cloud-appflowy_cloud-1  |    3:     0x55fe72414041 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd9a5b0c9c6b058c0
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:44:22
appflowy-cloud-appflowy_cloud-1  |    4:     0x55fe724416bf - core::fmt::rt::Argument::fmt::h0afc04119f252b53
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/rt.rs:138:9
appflowy-cloud-appflowy_cloud-1  |    5:     0x55fe724416bf - core::fmt::write::h50b1b3e73851a6fe
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/mod.rs:1094:21
appflowy-cloud-appflowy_cloud-1  |    6:     0x55fe724105b7 - std::io::Write::write_fmt::h184eaf275e4484f0
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/io/mod.rs:1714:15
appflowy-cloud-appflowy_cloud-1  |    7:     0x55fe72413e55 - std::sys_common::backtrace::_print::hf58c3a5a25090e71
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:47:5
appflowy-cloud-appflowy_cloud-1  |    8:     0x55fe72413e55 - std::sys_common::backtrace::print::hb9cf0a7c7f077819
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:34:9
appflowy-cloud-appflowy_cloud-1  |    9:     0x55fe724155c3 - std::panicking::default_hook::{{closure}}::h066adb2e3f3e2c07
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:269:22
appflowy-cloud-appflowy_cloud-1  |   10:     0x55fe72415354 - std::panicking::default_hook::h277fa2776900ff14
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:288:9
appflowy-cloud-appflowy_cloud-1  |   11:     0x55fe72415b49 - std::panicking::rust_panic_with_hook::hceaf38da6d9db792
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:705:13
appflowy-cloud-appflowy_cloud-1  |   12:     0x55fe72415a47 - std::panicking::begin_panic_handler::{{closure}}::h2bce3ed2516af7df
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:597:13
appflowy-cloud-appflowy_cloud-1  |   13:     0x55fe724144a6 - std::sys_common::backtrace::__rust_end_short_backtrace::h090f3faf8f98a395
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:151:18
appflowy-cloud-appflowy_cloud-1  |   14:     0x55fe72415792 - rust_begin_unwind
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
appflowy-cloud-appflowy_cloud-1  |   15:     0x55fe71591063 - core::panicking::panic_fmt::h4ec8274704d163a3
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
appflowy-cloud-appflowy_cloud-1  |   16:     0x55fe71591503 - core::result::unwrap_failed::h170bc2721a6c6ff2
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
appflowy-cloud-appflowy_cloud-1  |   17:     0x55fe715daf05 - appflowy_cloud::main::{{closure}}::h5d08a05b217815de
appflowy-cloud-appflowy_cloud-1  |   18:     0x55fe715d9b92 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::hf0e3f75cfa232c78
appflowy-cloud-appflowy_cloud-1  |   19:     0x55fe716ad847 - <core::pin::Pin<P> as core::future::future::Future>::poll::h3986a356dc03807f
appflowy-cloud-appflowy_cloud-1  |   20:     0x55fe716c848a - tokio::runtime::scheduler::current_thread::Context::enter::h595885efec386e4d
appflowy-cloud-appflowy_cloud-1  |   21:     0x55fe715d68ef - tokio::runtime::context::scoped::Scoped<T>::set::h752a37851ffdc298
appflowy-cloud-appflowy_cloud-1  |   22:     0x55fe71617e00 - tokio::runtime::context::set_scheduler::h0266dd634944a54a
appflowy-cloud-appflowy_cloud-1  |   23:     0x55fe716c888c - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::h18b8ae32d93cfafb
appflowy-cloud-appflowy_cloud-1  |   24:     0x55fe71603fcc - tokio::runtime::context::runtime::enter_runtime::hc0748e020bcc976d
appflowy-cloud-appflowy_cloud-1  |   25:     0x55fe716ac6b0 - tokio::runtime::runtime::Runtime::block_on::h6ecd33bdab2f0eb7
appflowy-cloud-appflowy_cloud-1  |   26:     0x55fe716c0433 - appflowy_cloud::main::h576b8397a210569b
appflowy-cloud-appflowy_cloud-1  |   27:     0x55fe71660013 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8eee212e491cb454
appflowy-cloud-appflowy_cloud-1  |   28:     0x55fe7166002d - std::rt::lang_start::{{closure}}::h632ac5dc0e60e8fe
appflowy-cloud-appflowy_cloud-1  |   29:     0x55fe724099bb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h75ba4244a1c7bb54
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:284:13
appflowy-cloud-appflowy_cloud-1  |   30:     0x55fe724099bb - std::panicking::try::do_call::h0a2baa36dea975a1
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
appflowy-cloud-appflowy_cloud-1  |   31:     0x55fe724099bb - std::panicking::try::h0e42aa233d4224d4
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
appflowy-cloud-appflowy_cloud-1  |   32:     0x55fe724099bb - std::panic::catch_unwind::hefdfd8f482606434
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
appflowy-cloud-appflowy_cloud-1  |   33:     0x55fe724099bb - std::rt::lang_start_internal::{{closure}}::h457959f0f91da23b
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:48
appflowy-cloud-appflowy_cloud-1  |   34:     0x55fe724099bb - std::panicking::try::do_call::h112cfd1acb38183b
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
appflowy-cloud-appflowy_cloud-1  |   35:     0x55fe724099bb - std::panicking::try::ha64f15b20cec18ca
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
appflowy-cloud-appflowy_cloud-1  |   36:     0x55fe724099bb - std::panic::catch_unwind::hbacc2b68ee2c119e
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
appflowy-cloud-appflowy_cloud-1  |   37:     0x55fe724099bb - std::rt::lang_start_internal::h5f408694586c2a05
appflowy-cloud-appflowy_cloud-1  |                                at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:20
appflowy-cloud-appflowy_cloud-1  |   38:     0x55fe716c0495 - main
appflowy-cloud-appflowy_cloud-1  |   39:     0x7fe3d66be1ca - <unknown>
appflowy-cloud-appflowy_cloud-1  |   40:     0x7fe3d66be285 - __libc_start_main
appflowy-cloud-appflowy_cloud-1  |   41:     0x55fe715bf951 - _start
appflowy-cloud-appflowy_cloud-1  |   42:                0x0 - <unknown>
```

**Comment by speed2exe** [comment]
Hi @vvatelot , we are in the in the middle of integrating the authentication server for the docker-compose build. Thanks for highlighting the issue, we are working on it

**Comment by vvatelot** [comment]
Thanks @speed2exe ! Let me know if I can help in anyway... :slightly_smiling_face:

**Comment by appflowy** [comment]
Hi @vvatelot. Thank you for contributing. You can follow the instruction that enables quick strart the docker. I will close this PR. Please feel free to open.

**Pull request closed without merging**
